### ISSUE TITLE
Should a progress bar appear when nsz.py runs correctly?

### ISSUE THREAD

**Issue by tonyrojas2007** [blawar/nsz#2]
I see that tqdm gets installed when running requirements.txt, so I was wondering if I should be seeing a progress bar when starting and during the compression stage. Or is it there in an If needed basis by piping it when running the command? I have no problem waiting for it to finish, but a progress bar would be nice to see.

**Comment by blawar** [comment]
code is hacked together from another project, nut, to get it working quickly.  i could add a progress bar though.

**Comment by tonyrojas2007** [comment]
If it's not too much trouble, i think it would really round out the app perfectly. But it's no biggie at all. Just got curious when I saw tqdm in there. Regardless, fantastic code and a huge fan of the project! It's a breeze to use.

**Comment by ReaperOfSouls1909** [comment]
i would love that also please

**Comment by blawar** [comment]
added https://github.com/blawar/nsz/commit/f28e1397aff8d0afe6f675b51d95209d1e3ce0fd
